apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  progressDeadlineSeconds: 30
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: gcr.io/scoot-networks-llc/sample-app
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10