apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: docker.prod.corp.scoot.co:5000/sample-app
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            cpu: 200m
            memory: 256Mi
